[build]
  command = "npm install && npm run build && node node_modules/pug-cli/index.js views/ --out ./views"
  functions="functions"

[[redirects]]
  from="/*"
  to="/.netlify/functions/server/:splat"
  status=200
  force = true
